"""empty message

Revision ID: 01462cdd1947
Revises: 326788ccd329
Create Date: 2024-07-11 18:54:27.808754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01462cdd1947'
down_revision = '326788ccd329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user', ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
